### ISSUE TITLE
[HW] Felipe Rojas

### ISSUE THREAD

**Issue by chekobil** [datastaxdevs/appdev-week1-todolist#154]
**Name:** Felipe Rojas
**Email:** felipe.arg@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/felipe-arg/>

Attach the homework screenshots below:
-----------------------------------------
### local version
![local](https://user-images.githubusercontent.com/484052/125543172-30d4fa69-95f4-4431-bb1b-dd5f8d63d229.jpeg)

Point 7, crashed with this message:
```
❯ npm exec astra-setup todos_workshop_db todos
Checking your credentials...

/Users/kobino/Desktop/DataStax/appdev-week1-todolist/node_modules/astra-setup/node_modules/@astrajs/rest/src/rest.js:164
    throw new Error(
          ^

Error: Request Failed: 404 page not found

Stack Trace: Request failed with status code 404
    at axiosRequest (/Users/kobino/Desktop/DataStax/appdev-week1-todolist/node_modules/astra-setup/node_modules/@astrajs/rest/src/rest.js:164:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.createClient (/Users/kobino/Desktop/DataStax/appdev-week1-todolist/node_modules/astra-setup/node_modules/@astrajs/rest/src/rest.js:97:24)
    at async astraClient.createClient (/Users/kobino/Desktop/DataStax/appdev-week1-todolist/node_modules/astra-setup/src/astra-setup.js:49:17)
    at async start (/Users/kobino/Desktop/DataStax/appdev-week1-todolist/node_modules/astra-setup/src/astra-setup.js:271:2)
```

So, my work is based on this repo <https://github.com/DataStax-Examples/todo-astra-jamstack-netlify>
and I made a local version, one on Gitpod and one on [Netlify](https://confident-banach-229ede.netlify.app/), all connected to the same database
### local
![local_todos](https://user-images.githubusercontent.com/484052/125543292-80fd8cda-d21c-48fe-a2f2-7921fddb43d7.jpeg)
### Gitpod
![gitpod_todos](https://user-images.githubusercontent.com/484052/125543306-8a4925b1-9c27-47f8-adf5-be3d7a141ae8.jpeg)
### Netlify
![netlify_todos](https://user-images.githubusercontent.com/484052/125543328-c870a2ec-bda8-49b3-aaf5-8e15800a5f50.jpeg)

**Comment by chekobil** [comment]
Ok I get it, on step 7 y was creating the .env file with the credentials, and it must be an empty file ...
now it´s working

![rest_todos_gitpod](https://user-images.githubusercontent.com/484052/125616082-ccfcb5bd-855e-4e71-bcfe-6ab6f7f5833b.jpeg)

**Comment by SonicDMG** [comment]
Really nice job working through this. Looks like you got it all working just fine. Did you ever get passed the astra-setup error early on? Seems like you must have if the database connection was working enough for you to do todo items in your list.

**Comment by HadesArchitect** [comment]
Hey **Felipe Rojas**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pTMzpgUOTEC86FtcW3YZqw
